[server]
maxUploadSize = 5
enableXsrfProtection = true

[theme]
base = "dark"
primaryColor = "#39E6E1"
backgroundColor = "#0B0F19"
secondaryBackgroundColor = "#131A2A"
textColor = "#E6EDF3"
font = "sans serif"
